NODE_ENV: production
SITE_URL: https://markets.example.com
SUPABASE_URL: https://your-project.supabase.co
NEXT_PUBLIC_REOWN_APPKIT_PROJECT_ID: replace-me
CLOB_URL: https://clob.kuest.com
RELAYER_URL: https://relayer.kuest.com
DATA_URL: https://data-api.kuest.com
USER_PNL_URL: https://user-pnl-api.kuest.com
COMMUNITY_URL: https://community.kuest.com
WS_CLOB_URL: wss://ws-subscriptions-clob.kuest.com
WS_LIVE_DATA_URL: wss://ws-live-data.kuest.com
NEXT_PUBLIC_FORK_OWNER_GUIDE: 'false'
